name: publish
on:
  workflow_dispatch:
    inputs:
      force:      
        description: Used to force a publish
        required: true
        type: boolean
        default: false
  push:
    branches:
      - main


permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        name: release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "@swimlane/docker-reference"

      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: bootstrap
        run: npm run bootstrap

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build:ts-definitions
      
      - name: test
        run: npm run test
      
      - name: coverage
        run: npm run test:coverage

      - name: publish
        if: ${{ steps.release.outputs.release_created || inputs.force }}
        run: |
          npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}

